### ISSUE TITLE
"Current session is missing data" when restoring a phone user

### ISSUE THREAD

**Issue by chimon2000** [supabase-community/gotrue-dart#29]
# Bug report

## Describe the bug

When attempting to restore the session, the user object is is returning null which causes the session to not be loaded.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Log in with a phone number user, using `verifyOTP`
2. Refresh the screen
3. Error should be printed when referencing `recoverSession` directly

## Expected behavior

The user information should be returned when a user has successfully logged in using an SMS token.  I noticed that this is not the case, when trying to print out the user info after a login, but I ignored it.

## Screenshots

n/a

## System information

- OS: Linux
- Browser (if applies): Chrome
- - Version of supabase: 0.1.0

## Additional context

n/a

**Comment by bdlukaa** [comment]
Can you try to call `SupabaseAuth.instance.auth.user`?

**Comment by dshukertjr** [comment]
Thank you @chimon2000 for reporting this issue. 

This bug seems to be related to https://github.com/supabase/gotrue/issues/141, where upon verifying via OTP, user object is not being returned from the server.

**Comment by chimon2000** [comment]
> Can you try to call `SupabaseAuth.instance.auth.user`?

When attempting to reference the user value either from the auth instance or the session it was coming back as null.

**Comment by dshukertjr** [comment]
@chimon2000 
Yeah, this is not a bug on the client side, but on the server side. Unfortunately at the moment, it looks like we would have to wait for the issue on the server side to get resolved.

**Comment by NeerajDana** [comment]
any update on this ??

**Comment by dshukertjr** [comment]
@NeerajDana 
This issue is cause by https://github.com/supabase/gotrue/issues/141 so unfortunately no updates at the moment.

**Comment by bdlukaa** [comment]
https://github.com/supabase/gotrue/issues/141#issuecomment-983637810

**Comment by MisterJimson** [comment]
So based on the last comment linked above, should the Supabase clients internally call `GET /user` in `verifyOTP` so the users of the client libraries don't need to work around the issue?

**Comment by bdlukaa** [comment]
According to https://github.com/supabase/gotrue/issues/141#issuecomment-983637810, https://github.com/supabase-community/gotrue-dart/pull/53 should fix this issue, no?
