### ISSUE TITLE
Missing documentation in comparison to javascript

### ISSUE THREAD

**Issue by vHanda** [supabase-community/gotrue-dart#33]
Hi. While implementing a signup flow (see #32), the docs did not indicate that the email validation required state is represented by the session and error values being null. This is indicated in the [javascript docs](https://supabase.io/docs/reference/javascript/auth-signup) however, I never thought of checking that website.

It would be better if these docs could be integrated within the dart code - https://pub.dev/documentation/gotrue/latest/gotrue/GoTrueClient/signUp.html

**Comment by dshukertjr** [comment]
Closing this issue, as we do have a section within our docs for dart language!
https://supabase.com/docs/reference/dart/auth-signup
