### ISSUE TITLE
SignUp does not return Session/User  object

### ISSUE THREAD

**Issue by krsikarya** [supabase-community/gotrue-dart#54]
I have enabled `Enable email confirmations`. 

When trying to SignUp a new user, not getting `Session or User` object. But based on this documentation
https://supabase.com/docs/reference/javascript/auth-signup (i know this is Javascript ref). 
- If "Email Confirmations" is turned on, a user is returned but session will be null. 

Auth 'users' table is also showing the registered user.  

Here is the code:
pubspec =>  supabase: ^0.2.14
```dart
final GotrueSessionResponse response = await _client.auth.signUp(email, pwd);
log('DATA : ${response.data?.toJson()}');
```
Result is NULL.

**Comment by dshukertjr** [comment]
Thanks @krsikarya for opening this issue. 

I was going to say we do have a dart documentation [here](https://supabase.com/docs/reference/dart/auth-signup), but found out that the dart doc also says the same thing `If "Email Confirmations" is turned on, a user is returned but session will be null`, which is not accurate, and I will submit a PR to fix it. 

Currently with the Dart library, you will not receive user or session object when the email confirmation is turned on as you can see [here](https://github.com/supabase-community/gotrue-dart/blob/main/lib/src/gotrue_api.dart#L38). This is probably not the ideal behavior, so maybe we can discuss here how we can solve this. 

We have discussed how to fix this in [this](https://github.com/supabase/supabase-flutter/issues/39#issuecomment-945022057) issue before by separating the `user` object within `GotrueSessionResponse` like the following. @bdlukaa what do you think about this approach? 

```dart
class GotrueSessionResponse extends GotrueResponse {
  Session? data;
  String? provider;
  String? url;
  User? user;

  GotrueSessionResponse({
    this.data,
    this.provider,
    this.url,
    User? user,
    GotrueError? error,
  }) : this.user = user ?? data?user,   super(error: error);
}
```
